### PR TITLE
Ci/e2e test for prs INTER-406

### PR DESCRIPTION
**Pull request by necipallef**
This PR adds a new workflow that runs e2e tests on a branch. Initial idea was to trigger this workflow manually and make it a required status check, but it is not straightforward to do at the moment ([discussion](https://stackoverflow.com/questions/74867744/how-can-i-attach-a-manual-workflow-run-to-a-pull-requests-status-checks)).

The Akamai property is created when a branch is created as we already know. Now, whenever a PR is created, e2e tests will run for the Akamai property.

Please note that, if PR is created before the property is active, then the e2e tests will fail, so one should wait to create a PR until the property is active.

### CODE REVIEW

**Comment by necipallef** [comment]
If all looks good, can we make this workflow file a required status check for this repo, @ilfa? The name of the job is "Build & Deploy & Test e2e for PR"

**Review by ilfa — DISMISSED** [review]

**Comment by ilfa** [comment]
> If all looks good, can we make this workflow file a required status check for this repo, @ilfa? The name of the job is "Build & Deploy & Test e2e for PR"

We have this option enabled, will specifying a specific workflow give us an additional advantage?

image

**Comment by necipallef** [comment]
I believe so. If status checks don't pass, we can still merge, but if they are marked as required, then we cannot merge AFAIK.

**Review by Orkuncakilkaya — DISMISSED** [review]

**Review by Orkuncakilkaya — APPROVED** [review]

**Review by ilfa — APPROVED** [review]

**Pull request merged**
